version: 2.1


jobs:
  developer-deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run:
          name: "NPM version check"
          command: npm --version
      - run:
          name: "Install Dependencies"
          command: . build/install_dependencies.sh
      - run:
          name: "Salesforce AUTH"
          command: . build/login_to_org.sh


workflows:
  developer-workflow:
    jobs:
      - developer-deploy: