version: 2.1


jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  test:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - run:
          name: "first test"
          command: npm --version
          #command: npm install -global sfdx-cli
          #command: sudo npm install -global sfdx-cli
          #command: npm install sfdx-cli -g
          #command: sfdx --version
      - run:
          name: "Install Dependencies"
          command: build/install_dependencies.sh

workflows:
  #say-hello-workflow:
    #jobs:
      #- say-hello
  test-workflow:
    jobs:
      - test