setup: true
version: 2.1
orbs:
  continuation: circleci/continuation@0.2.0
workflows:
  setup:
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/main.yml"
          parameters: /home/circleci/params.json
          pre-steps:
            - run:
                name: "main test"
                command: |
                  echo "test"
                  echo ${CIRCLE_PULL_REQUEST##*/}
                  echo $CIRCLE_BRANCH
                  echo "test"
                  if [ $CIRCLE_BRANCH <> "main" ]
                  then
                    echo "This is main"
                    curl --version

                    echo "google test"
                    curl google.com

                    echo "normal test"

                    curl \
                      -H "Accept: application/vnd.github+json" \
                      -H "Authorization: Bearer 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"\
                      https://api.github.com/repos/ArtBubnov/euro_test_2/pulls
                  else
                    echo "This is other branch"
                  fi



#                    IS_PR=false
#                  else
#                    IS_PR=true
#                  fi
#                 echo '{ "is_pr": '$IS_PR' }' >> /home/circleci/params.json