setup: true
version: 2.1
orbs:
  continuation: circleci/continuation@0.3.1
workflows:
  setup:
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/main.yml"
          parameters: /home/circleci/params.json
          pre-steps:
            - run:
                command: |
                  echo "test"
                  echo $CIRCLE_PULL_REQUEST
                  echo $CIRCLE_JOB
                  echo "---------"
                  echo $CI_PULL_REQUEST
                  echo $CI_PULL_REQUESTS
                  echo $CIRCLE_PULL_REQUEST
                  echo $CIRCLE_PULL_REQUESTS
                  echo "test"


                  if [ -z "${CIRCLE_PULL_REQUEST##*/}" ]
                  then
                    IS_PR=false
                  else
                    IS_PR=true
                  fi
                  echo $IS_PR
                  echo '{ "is_pr": '$IS_PR' }' >> /home/circleci/params.json
                  