version: 2.1


jobs:
  test:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run:
          name: "first test"
          command: npm --version
      - run:
          name: "Install Dependencies"
          command: . build/install_dependencies.sh
      - run:
          name: "Salesforce AUTH"
          command: . build/login_to_org.sh
      - run:
          name: "Deploy data to Dev Env"
          command: . build/deploy_to_developer_sf_org.sh

workflows:
  test-workflow:
    jobs:
      - test:
          filters:
            branches:
              only: main
              pull_request: true