version: 2.1

parameters:
  is_main:
    type: boolean
    default: false

jobs:
  on_main_actions:
    docker:
      - image: cimg/node:19.2.0
    steps:
        - checkout
        - run:
            name: get list of PR
            command: . build/test.sh
        - run:
            name: parce rest api call response\
            command: . build/parser.js

    



workflows:
   main-branch-workflow:
    jobs:
      - on_main_actions:
            name: on_main_actions